# Generated by Django 3.1.2 on 2021-02-18 12:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pfm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adenin', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('thymine', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('cytosine', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('guanine', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('matrix_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pfm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.pfm')),
            ],
        ),
    ]
