# Generated by Django 3.1.2 on 2021-02-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
