# Generated by Django 3.1.2 on 2021-02-18 15:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_matrix_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfm',
            name='adenin',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pfm',
            name='cytosine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pfm',
            name='guanine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pfm',
            name='thymine',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=None),
        ),
    ]
