# Generated by Django 3.1.2 on 2021-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210218_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfm',
            name='adenin',
            field=models.JSONField(null=True, verbose_name=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='pfm',
            name='cytosine',
            field=models.JSONField(null=True, verbose_name=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='pfm',
            name='guanine',
            field=models.JSONField(null=True, verbose_name=models.FloatField()),
        ),
        migrations.AlterField(
            model_name='pfm',
            name='thymine',
            field=models.JSONField(null=True, verbose_name=models.FloatField()),
        ),
    ]
